# PHP CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-php/
version: 2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    working_directory: /app
    docker:
      - image: ghcr.io/danielme85/lltdb-testbench
      - image: mariadb:latest
        environment:
          MYSQL_DATABASE: 'logtodb'
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      - image: mongo:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Run tests
          command: |
            cp .env.testing .env
            composer install --no-interaction
            composer dump-autoload
            dockerize -wait tcp://localhost:3306 -timeout 1m &&
            php -dpcov.enabled=1 -dpcov.directory="./src" -dpcov.exclude="~vendor~" ./vendor/bin/phpunit --coverage-clover coverage.xml
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov -t $CODECOV_TOKEN
