# PHP CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-php/
version: 2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    working_directory: /app
    docker:
      - image: ghcr.io/danielme85/lltdb-testbench
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - run:
          name: Start docker containers
          command: |
            docker-compose up -d mariadb mongo

      - run:
          name: Run tests
          command: |
            cp .env.testing .env
            composer install --no-interaction
            composer dump-autoload
            dockerize -wait tcp://mariadb:3306 -timeout 1m &&
            php -dpcov.enabled=1 -dpcov.directory="./src" -dpcov.exclude="~vendor~" ./vendor/bin/phpunit --verbose --debug --coverage-clover coverage.xml
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov -t $CODECOV_TOKEN
